services:
  # serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: gestaomonitoria_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promonitor
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
