services:
  # serviço da aplicação NodeJs
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: promonitor
      JWT_SECRET: secret_aqui
    depends_on:
      - db

  # serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: gestaomonitoria_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promonitor
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
