services:
  - name: app
    type: web
    env: node
    plan: starter
    buildCommand: "yarn install"
    startCommand: "yarn dev"
    envVars:
      - key: PORT
        value: 3000
      - key: MYSQL_HOST
        value: gestaomonitoria-db
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: promonitor
      - key: MYSQL_PORT
        value: 3306
      - key: JWT_SECRET
        value: secret_aqui
    autoDeploy: true
    healthCheckPath: "/healthcheck"
    disk:
      persistentStorage: false
    services:
      - name: gestaomonitoria-db

  - name: gestaomonitoria-db
    type: database
    plan: starter
    databaseName: promonitor
    user: root
    password: root
    startCommand: ""
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: promonitor
    disk:
      persistentStorage: true
    migrationsPath: ./database/init.sql